In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/ubuntu/notebooks/mlops_book_recommendation_system/data/open_ai_embeddings.csv")

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,...,1528,1529,1530,1531,1532,1533,1534,1535,1537,1538
0,-0.027731,0.042470,0.008717,0.006005,0.003524,-0.011976,0.025499,0.004350,0.002784,-0.020771,...,-0.001522,-0.055551,-0.029830,0.029234,0.005229,0.024660,0.046270,-0.004074,NaN,NaN
1,-0.033636,0.057242,-0.046693,0.006161,-0.012700,-0.030221,0.000629,0.043018,-0.024903,0.001636,...,-0.011662,-0.023584,0.000232,0.015337,0.005674,-0.049114,0.039603,-0.022287,NaN,NaN
2,-0.000989,0.046005,-0.038520,0.031684,-0.003147,-0.049453,-0.034260,-0.022698,-0.021684,0.002296,...,-0.003405,-0.020000,-0.029737,-0.005801,-0.006395,-0.006998,0.031461,-0.015730,NaN,NaN
3,0.005111,0.006698,0.006078,-0.008062,0.012402,0.011119,-0.058505,0.027798,-0.016893,-0.038939,...,0.002295,-0.055383,-0.012798,0.016380,-0.008986,-0.007564,0.030963,-0.003395,NaN,NaN
4,-0.038795,-0.015637,-0.055804,0.010385,-0.018284,0.015993,0.032960,-0.002102,0.018587,-0.021256,...,0.010023,-0.030690,-0.020500,0.042707,0.008348,0.015194,0.037736,0.006570,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37055,0.015166,0.064640,-0.022971,0.025832,0.012533,0.005859,-0.022013,-0.002755,-0.013407,0.014269,...,0.027747,-0.043045,-0.003911,0.004734,-0.017644,0.009588,0.004911,-0.015825,NaN,NaN
37056,-0.021004,0.024678,-0.062816,0.034320,-0.007740,-0.010017,-0.008390,-0.003726,0.000852,-0.052845,...,0.039542,0.005048,-0.007734,0.039909,-0.019272,0.005855,0.024323,0.019915,NaN,NaN
37057,-0.001714,0.055193,-0.013351,-0.009384,-0.032579,0.045978,0.023400,0.018829,-0.024428,0.000490,...,0.032168,-0.008882,-0.031201,0.033498,0.010436,0.010781,-0.008465,0.015141,NaN,NaN
37058,0.003824,0.075715,-0.022526,0.011342,-0.010533,0.002858,-0.019170,0.039958,-0.010726,0.020643,...,0.033125,-0.009380,-0.021681,0.019508,-0.023516,0.017359,0.020679,-0.032908,NaN,NaN
37059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN